### PR TITLE
Add database security monitoring dashboards

### PR DESCRIPTION
**Pull request by yota-p**
In this PR, I would like to add 2 dashboards for monitoring database security in Amazon Redshift. 

### Background
Currently Redshift users need to query system tables to monitor security features (e.g. user, schema, table, privileges) configured in Redshift. This requires querying multiple system tables and writing SQL. 
By using this dashboard, user will be able to navigate these information in Redshift quickly without writing SQL. 

### Amazon Redshift Identities and Objects dashboard

This dashboard will visualize identity (user/role/group) and database objects (schema/table etc). 

p1
p2

### Amazon Redshift Privileges dashboard

This dashboard will visualize privileges (who have what access). 

p3

### CODE REVIEW

**Comment by yota-p** [comment]
Hi team, 
There are workflows failing with `Error: Input required and not supplied: token`. 
Would someone from code owner help me resolve this, or can we just ignore?

Workflows are failing at:
https://github.com/grafana/redshift-datasource/blob/58116f0b519a68bda133f88e95ce7ceaa8308e5a/.github/workflows/issue_and_pr_commands.yml#L22
https://github.com/grafana/redshift-datasource/blob/09e086c86aa62392929a6384667b264981cc17ca/.github/workflows/issue_commands.yml#L23

As far as I searched, this error is happening because PR from forked repository cannot reference `secrets.GH_BOT_ACCESS_TOKEN` due to GitHub's security feature (same as #125 ). 
There's a workaround like using `pull_request_target` described in this article but I would like to hear your thoughts. 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by fridgepoet** [comment]
Thanks for looking into that; I don't think you need to worry about those checks for now.

I think you'll need to add these dashboards to the plugin.json so they will be suggested on the Dashboards page. Like:
```
"includes": [
    {
      "type": "dashboard",
      "name": "Redshift Monitoring",
      "path": "dashboards/redshift-monitoring.json"
    },
    {
      "type": "dashboard",
      "name": "Redshift Privileges",
      "path": "dashboards/redshift-privileges.json"
    },
    {
      "type": "dashboard",
      "name": "Redshift Identities and Objects",
      "path": "dashboards/redshift-identities-and-objects.json"
    }
  ],
```

**Comment by sunker** [comment]
Thanks for contributing @yota-p! 

When I test the dashboards, the query editors aren't loading properly. 
Screenshot from 2022-08-25 11-41-54

To work around this, you may need to tips the option `Export for sharing externally` when exporting your dashboard. 
Screenshot from 2022-08-25 11-38-54

**Comment by yota-p** [comment]
@fridgepoet @sunker Thank you for the response. I'll check plugin.json and dashboard definition file. 
I need some time to build the plugin on my side and test it. WIll let you know once ready.

**Comment by yota-p** [comment]
@fridgepoet 
Updated plugin.json. I built the plugin locally and confirmed the dashboards can be imported & are working.
ScreenShot 2022-08-26 at 21 37 29

**Comment by yota-p** [comment]
@sunker 
Interesting, I didn't see the same error. The dashboards are loading properly on when I tested. 
Would you try again with the latest commit? 

ScreenShot 2022-08-26 at 21 43 40

I used the option `Export for sharing externally`. FYI, I also made changes to the JSON manually since exported file still contains environment specific info (e.g. datasource uid). I can still load the dashboard properly so I think it's not the cause here. Changes I made are:

- Removed `__inputs`, `__elements`, `__requires`, `iteration`
- Replaced `“datasource”: {“type”: xxx, “uid”: xxx}` to `"datasource": "${ds}"`
- Replaced values of `templating.list[0].current.text`, `templating.list[0].current.value` to `default`

**Comment by kevinwcyu** [comment]
Hi @yota-p, could you change the following in the dashboards

```json
"datasource": "${ds}"
```
to the following

```json
"datasource": {
  "type": "grafana-redshift-datasource",
  "uid": "${ds}"
},
```

I suspect that's what's causing @sunker to not be able to see the correct query editor. Just a bit of background. We changed the shape of the `datasource` some time in v8.3.x of Grafana I believe. It used to be a string, but now it's an object with the `type` and `uid` property. I think what's happening is when we read the `datasource` property after importing the dashboard, it's setting the datasource as the whatever is set as the default datasource for the Grafana instance.

I was seeing the same issue as @sunker when I changed my default datasource to a different plugin, but using the new format for the `datasource` property fixed it.

**Comment by yota-p** [comment]
@kevinwcyu Thank you for the suggestion. I changed the format for `datasource` property and confirmed it's loading properly on my end (I'm using latest v9.1.1). Would you review?

**Review by kevinwcyu — APPROVED** [review]
Thanks for the contribution @yota-p. It looks good from my end.

@sunker, could you check to see if the query editor is loading for you when you get a moment?

**Review by sunker — APPROVED** [review]
Looks good! Thanks for contributing @yota-p.

**Comment by yota-p** [comment]
Great, thank you team!

**Comment by yota-p** [comment]
Hi @sunker @kevinwcyu , 
Do you have a plan when to release the next version? 

This feature is merged but not released yet. If possible, I want this feature to be released by the end of September (not a hard limit tho).

**Comment by sunker** [comment]
Yes it was just released in [1.2.0](https://grafana.com/grafana/plugins/grafana-redshift-datasource/). Thanks again for contributing!

**Pull request merged**
