### PR TITLE
upgrade all dependencies to latest compatible versions

### PR DESCRIPTION
**Pull request by kishaningithub**
Addresses https://github.com/grafana/grafana-aws-sdk/issues/50#issuecomment-1084317640

### CODE REVIEW

**Comment by kishaningithub** [comment]
This is the issue which is failing the pipeline. Need help to resolve the same. Thanks in advance :-)

Screenshot
Screenshot 2022-03-31 at 6 13 40 PM

**Comment by kishaningithub** [comment]
@andresmgot I think the problem is because [create-or-update-comment github action](https://github.com/peter-evans/create-or-update-comment) does not have permission to update issue status in another repository which is linked by this PR.

**Comment by kishaningithub** [comment]
Since the above did not fix it, have changed the PR description to what was there originally

@fridgepoet Would need your help for sure to fix it

**Review by andresmgot — APPROVED** [review]
Thanks for the details! We can merge this in the meantime

**Comment by kishaningithub** [comment]
@andresmgot Thanks for the merge! :-) Can you kindly tag a new release for this? :-)

**Comment by andresmgot** [comment]
Just released here: https://github.com/grafana/redshift-datasource/releases

**Pull request merged**
